// Code generated by counterfeiter. DO NOT EDIT.
package conditionfakes

import (
	"sync"

	"github.com/dpb587/slack-delegate-bot/logic/condition"
	"github.com/dpb587/slack-delegate-bot/message"
)

type FakeCondition struct {
	EvaluateStub        func(message.Message) (bool, error)
	evaluateMutex       sync.RWMutex
	evaluateArgsForCall []struct {
		arg1 message.Message
	}
	evaluateReturns struct {
		result1 bool
		result2 error
	}
	evaluateReturnsOnCall map[int]struct {
		result1 bool
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeCondition) Evaluate(arg1 message.Message) (bool, error) {
	fake.evaluateMutex.Lock()
	ret, specificReturn := fake.evaluateReturnsOnCall[len(fake.evaluateArgsForCall)]
	fake.evaluateArgsForCall = append(fake.evaluateArgsForCall, struct {
		arg1 message.Message
	}{arg1})
	fake.recordInvocation("Evaluate", []interface{}{arg1})
	fake.evaluateMutex.Unlock()
	if fake.EvaluateStub != nil {
		return fake.EvaluateStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.evaluateReturns.result1, fake.evaluateReturns.result2
}

func (fake *FakeCondition) EvaluateCallCount() int {
	fake.evaluateMutex.RLock()
	defer fake.evaluateMutex.RUnlock()
	return len(fake.evaluateArgsForCall)
}

func (fake *FakeCondition) EvaluateArgsForCall(i int) message.Message {
	fake.evaluateMutex.RLock()
	defer fake.evaluateMutex.RUnlock()
	return fake.evaluateArgsForCall[i].arg1
}

func (fake *FakeCondition) EvaluateReturns(result1 bool, result2 error) {
	fake.EvaluateStub = nil
	fake.evaluateReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeCondition) EvaluateReturnsOnCall(i int, result1 bool, result2 error) {
	fake.EvaluateStub = nil
	if fake.evaluateReturnsOnCall == nil {
		fake.evaluateReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 error
		})
	}
	fake.evaluateReturnsOnCall[i] = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeCondition) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.evaluateMutex.RLock()
	defer fake.evaluateMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeCondition) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ condition.Condition = new(FakeCondition)
