// Code generated by counterfeiter. DO NOT EDIT.
package handlerfakes

import (
	"sync"

	"github.com/dpb587/slack-delegate-bot/cmd/delegatebot/handler"
	"github.com/dpb587/slack-delegate-bot/pkg/message"
)

type FakeHandler struct {
	IsApplicableStub        func(message.Message) (bool, error)
	isApplicableMutex       sync.RWMutex
	isApplicableArgsForCall []struct {
		arg1 message.Message
	}
	isApplicableReturns struct {
		result1 bool
		result2 error
	}
	isApplicableReturnsOnCall map[int]struct {
		result1 bool
		result2 error
	}
	ExecuteStub        func(*message.Message) (handler.MessageResponse, error)
	executeMutex       sync.RWMutex
	executeArgsForCall []struct {
		arg1 *message.Message
	}
	executeReturns struct {
		result1 handler.MessageResponse
		result2 error
	}
	executeReturnsOnCall map[int]struct {
		result1 handler.MessageResponse
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeHandler) IsApplicable(arg1 message.Message) (bool, error) {
	fake.isApplicableMutex.Lock()
	ret, specificReturn := fake.isApplicableReturnsOnCall[len(fake.isApplicableArgsForCall)]
	fake.isApplicableArgsForCall = append(fake.isApplicableArgsForCall, struct {
		arg1 message.Message
	}{arg1})
	fake.recordInvocation("IsApplicable", []interface{}{arg1})
	fake.isApplicableMutex.Unlock()
	if fake.IsApplicableStub != nil {
		return fake.IsApplicableStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.isApplicableReturns.result1, fake.isApplicableReturns.result2
}

func (fake *FakeHandler) IsApplicableCallCount() int {
	fake.isApplicableMutex.RLock()
	defer fake.isApplicableMutex.RUnlock()
	return len(fake.isApplicableArgsForCall)
}

func (fake *FakeHandler) IsApplicableArgsForCall(i int) message.Message {
	fake.isApplicableMutex.RLock()
	defer fake.isApplicableMutex.RUnlock()
	return fake.isApplicableArgsForCall[i].arg1
}

func (fake *FakeHandler) IsApplicableReturns(result1 bool, result2 error) {
	fake.IsApplicableStub = nil
	fake.isApplicableReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeHandler) IsApplicableReturnsOnCall(i int, result1 bool, result2 error) {
	fake.IsApplicableStub = nil
	if fake.isApplicableReturnsOnCall == nil {
		fake.isApplicableReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 error
		})
	}
	fake.isApplicableReturnsOnCall[i] = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeHandler) Execute(arg1 *message.Message) (handler.MessageResponse, error) {
	fake.executeMutex.Lock()
	ret, specificReturn := fake.executeReturnsOnCall[len(fake.executeArgsForCall)]
	fake.executeArgsForCall = append(fake.executeArgsForCall, struct {
		arg1 *message.Message
	}{arg1})
	fake.recordInvocation("Execute", []interface{}{arg1})
	fake.executeMutex.Unlock()
	if fake.ExecuteStub != nil {
		return fake.ExecuteStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.executeReturns.result1, fake.executeReturns.result2
}

func (fake *FakeHandler) ExecuteCallCount() int {
	fake.executeMutex.RLock()
	defer fake.executeMutex.RUnlock()
	return len(fake.executeArgsForCall)
}

func (fake *FakeHandler) ExecuteArgsForCall(i int) *message.Message {
	fake.executeMutex.RLock()
	defer fake.executeMutex.RUnlock()
	return fake.executeArgsForCall[i].arg1
}

func (fake *FakeHandler) ExecuteReturns(result1 handler.MessageResponse, result2 error) {
	fake.ExecuteStub = nil
	fake.executeReturns = struct {
		result1 handler.MessageResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeHandler) ExecuteReturnsOnCall(i int, result1 handler.MessageResponse, result2 error) {
	fake.ExecuteStub = nil
	if fake.executeReturnsOnCall == nil {
		fake.executeReturnsOnCall = make(map[int]struct {
			result1 handler.MessageResponse
			result2 error
		})
	}
	fake.executeReturnsOnCall[i] = struct {
		result1 handler.MessageResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeHandler) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.isApplicableMutex.RLock()
	defer fake.isApplicableMutex.RUnlock()
	fake.executeMutex.RLock()
	defer fake.executeMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeHandler) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ handler.Handler = new(FakeHandler)
