#!/bin/bash

# args: [version]

set -eu

cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.."
version="${1:-0.0.0}"

if [ -z "${bin_list:-}" ]; then
  bin_list="$( ls cmd )"
fi

if [ -z "${os_list:-}" ]; then
  os_list="darwin linux windows"
fi

if [ -z "${arch_list:-}" ]; then
  arch_list="amd64"
fi

rm -fr tmp/build/*
mkdir -p tmp/build

commit=$( git rev-parse HEAD | cut -c-10 )$( git diff-index --quiet HEAD -- || echo "+dirty" )
built=$( date -u +%Y-%m-%dT%H:%M:%S+00:00 )

export CGO_ENABLED=0

for name in $bin_list ; do
  for os in $os_list ; do
    for arch in $arch_list ; do
      filename=$name-$version-$os-$arch

      if [ "$os" == "windows" ]; then
        filename=$filename.exe
      fi

      echo "$filename"
      GOOS=$os GOARCH=$arch go build \
        -ldflags "
          -X github.com/dpb587/slack-delegate-bot/pkg/cli/app.name=$name \
          -X github.com/dpb587/slack-delegate-bot/pkg/cli/app.semver=$version \
          -X github.com/dpb587/slack-delegate-bot/pkg/cli/app.commit=$commit \
          -X github.com/dpb587/slack-delegate-bot/pkg/cli/app.built=$built \
        " \
        -o tmp/build/$filename \
        ./cmd/$name
    done
  done
done
