// Code generated by counterfeiter. DO NOT EDIT.
package interruptfakes

import (
	"sync"

	"github.com/dpb587/slack-delegate-bot/logic/interrupt"
	"github.com/dpb587/slack-delegate-bot/message"
)

type FakeInterrupt struct {
	LookupStub        func(message.Message) ([]interrupt.Interruptible, error)
	lookupMutex       sync.RWMutex
	lookupArgsForCall []struct {
		arg1 message.Message
	}
	lookupReturns struct {
		result1 []interrupt.Interruptible
		result2 error
	}
	lookupReturnsOnCall map[int]struct {
		result1 []interrupt.Interruptible
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeInterrupt) Lookup(arg1 message.Message) ([]interrupt.Interruptible, error) {
	fake.lookupMutex.Lock()
	ret, specificReturn := fake.lookupReturnsOnCall[len(fake.lookupArgsForCall)]
	fake.lookupArgsForCall = append(fake.lookupArgsForCall, struct {
		arg1 message.Message
	}{arg1})
	fake.recordInvocation("Lookup", []interface{}{arg1})
	fake.lookupMutex.Unlock()
	if fake.LookupStub != nil {
		return fake.LookupStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.lookupReturns.result1, fake.lookupReturns.result2
}

func (fake *FakeInterrupt) LookupCallCount() int {
	fake.lookupMutex.RLock()
	defer fake.lookupMutex.RUnlock()
	return len(fake.lookupArgsForCall)
}

func (fake *FakeInterrupt) LookupArgsForCall(i int) message.Message {
	fake.lookupMutex.RLock()
	defer fake.lookupMutex.RUnlock()
	return fake.lookupArgsForCall[i].arg1
}

func (fake *FakeInterrupt) LookupReturns(result1 []interrupt.Interruptible, result2 error) {
	fake.LookupStub = nil
	fake.lookupReturns = struct {
		result1 []interrupt.Interruptible
		result2 error
	}{result1, result2}
}

func (fake *FakeInterrupt) LookupReturnsOnCall(i int, result1 []interrupt.Interruptible, result2 error) {
	fake.LookupStub = nil
	if fake.lookupReturnsOnCall == nil {
		fake.lookupReturnsOnCall = make(map[int]struct {
			result1 []interrupt.Interruptible
			result2 error
		})
	}
	fake.lookupReturnsOnCall[i] = struct {
		result1 []interrupt.Interruptible
		result2 error
	}{result1, result2}
}

func (fake *FakeInterrupt) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.lookupMutex.RLock()
	defer fake.lookupMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeInterrupt) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ interrupt.Interrupt = new(FakeInterrupt)
